services:
  # üêò Base de donn√©es PostgreSQL
  postgres:
    image: postgres:17-alpine  # Remplace par 18-alpine quand elle sera dispo
    container_name: template_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: template_db
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  # üìß Serveur Mail de test (Mailpit)
  mailpit:
    image: axllent/mailpit
    container_name: template_mail
    restart: unless-stopped
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1 # Accepte n'importe quel user/pass
    ports:
      - "8025:8025" # Interface Web (UI)
      - "1025:1025" # Port SMTP (pour le backend)
    volumes:
      - ./data/mailpit:/data

volumes:
  postgres_data:
  mailpit_data:
